In [25]:
import re
import os
import nltk
import numpy as np
import tensorflow as tf
import pandas as pd
from tensorflow import keras
from tqdm import tqdm
from tensorflow.keras.layers.experimental.preprocessing import TextVectorization
from gensim.models.keyedvectors import KeyedVectors
word_vect = KeyedVectors.load_word2vec_format("SO_vectors_200.bin", binary=True)

In [26]:
idToTagIndex = {}          #dict mapping post ID to a list of tag indices
tagToTagIndex = {}         #dict mapping tag to tag index

In [27]:
import math
def truncate(number, digits) -> float:
    stepper = 10.0 ** digits
    return math.trunc(stepper * number) / stepper

In [28]:
with open("stacksample/Questions-ascii-1M.csv") as question_input:
    questions_data = pd.read_csv(question_input, engine='python')

    print(questions_data.columns)
    questions_data = questions_data[['Id', 'Body']]
    questions_data.insert(len(questions_data.columns), 'Code', "")
    
    a = re.compile(r'<pre><code>([^<]*)</code></pre>')
    b = re.compile(r'<.*?>')
    questions_data['Code'] = questions_data['Body'].apply(lambda x: ' '.join(re.findall(a, x)))

    def clean(text):
        x = re.sub(a, '', text)
        x = re.sub(b, '', x)
        x = x.replace('\n\n', '\n')
        return x
    questions_data['Body'] = questions_data['Body'].apply(clean)
    
#     questions_data['Body'] = questions_data['Body'].apply(nltk.tokenize.word_tokenize) #need to fix: don't convert
#     # C#, C++ to C
#     questions_data['Body'] = questions_data['Body'].apply(lambda x: [word for word in x if word.isalnum()])
#     questions_data['Body'] = questions_data['Body'].apply(lambda x: [word.lower() for word in x])

Index(['Id', 'OwnerUserId', 'CreationDate', 'ClosedDate', 'Score', 'Title',
       'Body'],
      dtype='object')


In [29]:
from collections import defaultdict

idToTagIndex = {}          #dict mapping post ID to a list of tag indices
tagToTagIndex = {}         #dict mapping tag to tag index
tagIndexToTag = {}
tagToFrequency = defaultdict(lambda: 0)

with open("stacksample/tags-1M.csv") as tag_input:
    tag_data = pd.read_csv(tag_input)
    tagIndex = 0
    for index, row in tqdm(tag_data.iterrows()):
        currId = int(row[0])
        currTag = row[1]
        if currTag not in tagToTagIndex:
            tagToTagIndex[currTag] = tagIndex
            tagIndexToTag[tagIndex] = currTag
            currTagIndex = tagIndex
            tagIndex += 1

        else:
            currTagIndex = tagToTagIndex[currTag]  
        
        tagToFrequency[currTagIndex] += 1        
    
        if currId not in idToTagIndex.keys():
            idToTagIndex[currId] = [tagToTagIndex[row[1]]]
        else:
            idToTagIndex[currId].append(tagToTagIndex[row[1]])
            

152759it [00:13, 11181.25it/s]


In [15]:
print("Number of examples: ", len(idToTagIndex))

Number of examples:  53203


In [30]:
# find 10 most common tags

tagToFrequencyList = []

for key, value in tagToFrequency.items():
    temp = [key, value]
    tagToFrequencyList.append(temp)
    
tagToFrequencyList.sort(reverse=True, key=lambda x: x[1])

for tag in tagToFrequencyList[:10]:
    print(f"{tagIndexToTag[tag[0]]} ({tag[0]}): {tag[1]} times")
    
mostCommonTags = {}
for counter, tag in enumerate(tagToFrequencyList[:10]):   #currently takes top 10 tags
    mostCommonTags[tag[0]] = counter


c# (14): 6722 times
java (89): 3858 times
.net (15): 3598 times
php (76): 3223 times
asp.net (8): 3041 times
javascript (132): 2852 times
c++ (18): 2509 times
jquery (370): 2198 times
iphone (607): 2111 times
python (196): 2070 times


In [31]:
# list(idToTagIndex.values())[:10]
print(mostCommonTags)

{14: 0, 89: 1, 15: 2, 76: 3, 8: 4, 132: 5, 18: 6, 370: 7, 607: 8, 196: 9}


In [32]:
idToTenTags = {}

for postId, tags in idToTagIndex.items():
    containsTopTenTags = [mostCommonTags[tag] for tag in tags if tag in mostCommonTags.keys()]
    idToTenTags[postId] = containsTopTenTags
    
questions_data['Top-Tags'] = questions_data['Id'].apply(lambda x: idToTenTags[x])

print(questions_data)

            Id                                               Body  \
0           80  I've written a database generation script in S...   
1           90  Are there any really good tutorials explaining...   
2          120  Has anyone got experience creating SQL-based A...   
3          180  This is something I've pseudo-solved many time...   
4          260  I have a little game written in C#. It uses a ...   
...        ...                                                ...   
53198  2495810  I'm going to host an app on a shared host and ...   
53199  2495870  I use MouseMove event to move objects(say labe...   
53200  2495890  I have dragged a empty asp.net table onto my w...   
53201  2495910  I want to log some seemingly random errors I'm...   
53202  2496040  I have a php array that has a bunch of data th...   

                                                    Code Top-Tags  
0      Create Table tRole (\n      roleID integer Pri...       []  
1                                  

In [57]:
from tensorflow.keras.layers.experimental.preprocessing import TextVectorization

vectorizer = TextVectorization(max_tokens=20000, output_sequence_length=200)
text_ds = tf.data.Dataset.from_tensor_slices(questions_data['Body'].values.tolist())
vectorizer.adapt(text_ds)
vectorizer.get_vocabulary()[:10]

['', '[UNK]', 'the', 'to', 'i', 'a', 'is', 'and', 'in', 'of']

In [60]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MultiLabelBinarizer
mlb = MultiLabelBinarizer()

questions_X = vectorizer(np.array([[s] for s in questions_data['Body'].values])).numpy()
questions_y = mlb.fit_transform(np.array(questions_data['Top-Tags'].values))
print(questions_y[:5])

train_X, test_X, train_y, test_y = train_test_split(questions_X, questions_y, train_size=0.75, random_state=200)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [1 0 1 0 0 0 0 0 0 0]]


In [38]:
output = vectorizer([["I tried running this line of code, but I'm receiving a null pointer exception"]])
output.numpy()

array([[   4,  124,  176,   12,  166,    9,   40,   15,   26, 1701,    5,
         393,  848,  291,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0, 

In [63]:
voc = vectorizer.get_vocabulary()
word_index = dict(zip(voc, range(len(voc))))
print(word_index["hello"])

1517


In [64]:
test = ["this", "line", "of", "code"]
[word_index[w] for w in test] 

[12, 166, 9, 40]

In [65]:
num_tokens = len(voc) + 2
print(num_tokens)
embedding_dim = 200
hits = 0
misses = 0

embedding_matrix = np.zeros((num_tokens, embedding_dim))
for word, i in word_index.items():
    try:
        embedding_vector = word_vect.get_vector(word)
        # Words not found in embedding index will be all-zeros.
        # This includes the representation for "padding" and "OOV"
        embedding_matrix[i] = embedding_vector
        hits += 1
    except:
        misses += 1
print("Converted %d words (%d misses)" % (hits, misses))

20002
Converted 18657 words (1343 misses)


In [67]:
from tensorflow.keras.layers import Embedding

embedding_layer = Embedding(
    num_tokens,
    embedding_dim,
    embeddings_initializer=keras.initializers.Constant(embedding_matrix),
    trainable=False,
)

In [128]:
from tensorflow.keras import layers, Sequential

int_sequences_input = keras.Input(shape=(None,), dtype="int64")
embedded_sequences = embedding_layer(int_sequences_input)
x = layers.Conv1D(128, 5, activation="relu")(embedded_sequences)
x = layers.MaxPooling1D(5)(x)
x = layers.Conv1D(128, 5, activation="relu")(x)
x = layers.MaxPooling1D(5)(x)
x = layers.Conv1D(128, 5, activation="relu")(x)
x = layers.GlobalMaxPooling1D()(x)
x = layers.Dense(128, activation="relu")(x)
x = layers.Dropout(0.5)(x)
x = layers.Dropout(0.5)(x)
preds = layers.Dense(len(mostCommonTags))(x) #change to all tags
preds = layers.Softmax(axis=-1)(preds)
# model = keras.Model(int_sequences_input, preds)
model = Sequential()
model.add(embedding_layer)
model.add(layers.SpatialDropout1D(0.2))
model.add(layers.LSTM(2, dropout=0.2, recurrent_dropout=0.2))
model.add(layers.Dense(len(mostCommonTags), activation='softmax'))

model.summary()

Model: "functional_13"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_22 (InputLayer)        [(None, None)]            0         
_________________________________________________________________
embedding_1 (Embedding)      (None, None, 200)         4000400   
_________________________________________________________________
conv1d_48 (Conv1D)           (None, None, 128)         128128    
_________________________________________________________________
max_pooling1d_32 (MaxPooling (None, None, 128)         0         
_________________________________________________________________
conv1d_49 (Conv1D)           (None, None, 128)         82048     
_________________________________________________________________
max_pooling1d_33 (MaxPooling (None, None, 128)         0         
_________________________________________________________________
conv1d_50 (Conv1D)           (None, None, 128)       

In [130]:
from sklearn.utils import class_weight
import tensorflow.keras.backend as K

import tensorflow.keras.callbacks as cbks
class CustomMetrics(cbks.Callback):

    def on_epoch_end(self, epoch, logs=None):
        for k in logs:
            print(logs[k])

def custom_metric(y_true, y_pred):
    print("y_true")
    print(K.print_tensor(y_true))
    print("y_pred")
    print(K.print_tensor(y_pred))
    
  
    

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              #loss = custom_loss,
              metrics = [tf.keras.metrics.TopKCategoricalAccuracy(k=5)]) 
              #metrics = 'accuracy'
              #metrics = custom_metric)                

weights = {}

for i in range(10):
    weights[i] = (1 / tagToFrequencyList[i][1])

model.fit(train_X, train_y, batch_size=128, epochs=1, validation_data=(test_X, test_y), class_weight=weights, callbacks = [CustomMetrics()])

312/312 [==============================] - ETA: 0s - loss: 5.5621e-05 - top_k_categorical_accuracy: 0.75815.562078149523586e-05
0.7581073641777039
0.20028650760650635
0.9373731017112732
312/312 [==============================] - 48s 155ms/step - loss: 5.5621e-05 - top_k_categorical_accuracy: 0.7581 - val_loss: 0.2003 - val_top_k_categorical_accuracy: 0.9374


In [132]:
string_input = keras.Input(shape=(1,), dtype="string")
x = vectorizer(string_input)
preds = model(x)
end_to_end_model = keras.Model(string_input, preds)

probabilities = end_to_end_model.predict(
#    ["I wanted to open my app without safari system alert but I found out that is impossible. so i decided to handle this alert event but I couldn't find the way. if I click [open], then safari open App, but if I click [cancel], then 'appCheckTimer' will be executed, then safari moves to 'some page's url'. if there is no way to not open this alert, I want to handle this alert's button event, when user click [cancel], I just want to stay that page. that alert is not opened by me, it's by safari So I can't handle it."]
#     ["Dropped my iphone again :("]
    ["my name is Varuni"]
)

for i, prob in np.ndenumerate(probabilities):
    print('{:<16}  {:<16}'.format(tagIndexToTag[tagToFrequencyList[i[1]][0]], truncate(prob, 3)))
print(f"\nMost likely tag: {tagIndexToTag[tagToFrequencyList[np.argmax(probabilities)][0]]}")

c#                0.11            
java              0.101           
.net              0.094           
php               0.115           
asp.net           0.104           
javascript        0.099           
c++               0.085           
jquery            0.083           
iphone            0.1             
python            0.104           

Most likely tag: php
